### ISSUE TITLE
working_dir ignored

### ISSUE THREAD

**Issue by nikhil-jain** [emcastillo/BSC-Tizona#1]
It seems to me that working_dir variable is not being used to create the output location for a given run, ie instead of being named OUT_DIR/working_dir/name.out, the output files are being named OUT_DIR/name.out.

**Comment by emcastillo** [comment]
Fixed with commit [link](https://github.com/emcastillo/Tizona/commit/138c3ab9d823cfd79a3534db241d9e87d2cb2661)
